name: s3-depl

on:
  push:
    branches:
      - master

jobs:
  node-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm install 
        #npm test
        #env:
           #CI: true 
           
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
 
      #- name: Deploy app build to S3 bucket
        #run: aws s3 sync ./ s3://rialto-api-s3 --delete
